/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zsshen_bmi_MainApplication */

#ifndef _Included_org_zsshen_bmi_MainApplication
#define _Included_org_zsshen_bmi_MainApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zsshen_bmi_MainApplication
 * Method:    calcInManiApplication
 * Signature: (CII)I
 */
JNIEXPORT jint JNICALL Java_org_zsshen_bmi_MainApplication_calcInManiApplication
  (JNIEnv *, jobject, jchar, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
